# Welcome to Serverless!

service: backend-message

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 2048
  stage: dev
  # timeout: 15
  region: ap-south-1
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      MONGODB_URL_PROD: mongodb+srv://ashifrez12:RARb3x5ClXI5r6xH@cluster0.78v4kus.mongodb.net/tuteck_messager?retryWrites=true&w=majority
      NODE_ENV: development
      SECRET_KEY: ddo9u2ue9e012u0e210801ueqwu021830912
      email: ashif.ewp@gmail.com
      password: kodooaiupyvssjdh
      SALT: 12
